### ISSUE TITLE
Blocks Docker's Overlay Network

### ISSUE THREAD

**Issue by ProjectInitiative** [LolHens/docker-swarm-keepalived#1]
I have noticed when running this service on any node in a docker swarm, the docker overlay network begins to behave very strangely. For instance, containers are no longer able to talk to each other across nodes or locally. Problem goes away when docker-swarm-keepalived service is stopped. 

I am not really sure what to provide to help describe the problem as clusters and swarms can quickly become pretty complex.

**Comment by LolHens** [comment]
That is really weird. I have tried this on several different swarm configurations and never came across this behavour. You could try to run [osixia/docker-keepalived](https://github.com/osixia/docker-keepalived) manually [like this](https://github.com/LolHens/docker-swarm-keepalived/blob/main/entrypoint.sh#L64) to see if the problem persists.

**Comment by ProjectInitiative** [comment]
I ran the [osixia/docker-keepalived](https://github.com/osixia/docker-keepalived) image manually on multiple nodes, and just on a single node. Tried it with two different clusters, and both broke. I am currently in the process of writing up a full (hopefully) reproducible instruction set and will tack it to the osixia repository. I will post a link when I am done.

**Comment by ProjectInitiative** [comment]
Here is the [link](https://github.com/osixia/docker-keepalived/issues/52) to the issue I have created.

**Comment by ProjectInitiative** [comment]
Closing out issue, I figured out the problem. TL;DR there was a subnet mismatch configuration that somehow propagated throughout all of the environment variables. It was only off by a few digits but knocked out the required IP address of the manager nodes.
